AWSTemplateFormatVersion: 2010-09-09
Description: Part 1 - Build a webapp stack with CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05ba3a39a75be1ec4 # Ubuntu 20.04 AMI
      InstanceType: t2.micro